name: Rust CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Configurar Rust Toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Configurar Caché de Cargo
        uses: Swatinem/rust-cache@v2
        with:
          shared-key: "cargo-cache"

      - name: Verificar formato
        run: cargo fmt --check

      - name: Analizar código
        run: cargo clippy -- -D warnings

      - name: Ejecutar test del server
        run: cargo test -p servidor
